# Site
repository: fisoluwajana/fisoluwajana.github.io
#favicon: images/favicon.ico

# Personal info
name: Fisayo Oluwajana
title: DevOps Engineer
email: fisoluwajana@gmail.com

darkmode: false

# Social links
#Â twitter_username: facespics
github_username:  fisoluwajana
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: fisoluwajana
linkedin_username: fisayooluwajana
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a competent and driven DevOps Engineer with a passion for promoting standards in CI/CD, Infrastructure as Code and Configuration Management to accelerate product delivery.
  
  I am certified across multiple cloud vendors and I'm always keen to learn new technologies.

  My key skills are <mark>AWS</mark>, <mark>Python</mark>, <mark>Terraform</mark> and <mark>Jenkins</mark>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Music
   - Gaming
   - CrossFit

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
